"""
Data models for normalized execution events.
"""

from pydantic import BaseModel
from typing import List, Optional, Dict, Any
from datetime import datetime
from enum import Enum


class EventType(str, Enum):
    """Types of events that can occur during node execution."""
    STARTED = "started"
    FINISHED = "finished"
    RETRY = "retry"
    ERROR = "error"
    SKIPPED = "skipped"


class EventStatus(str, Enum):
    """Status of a completed event."""
    SUCCESS = "success"
    ERROR = "error"
    TIMEOUT = "timeout"


class ExecutionEvent(BaseModel):
    """
    Normalized event representing a single node execution event.

    Each node execution generates at least 2 events:
    - STARTED: when the node begins execution
    - FINISHED/ERROR: when the node completes
    """
    execution_id: Optional[str] = None  # UUID from database, set after storage
    node_id: str
    event_type: EventType
    timestamp: datetime
    duration_ms: Optional[int] = None
    status: Optional[EventStatus] = None
    error_message: Optional[str] = None
    retry_attempt: int = 0
    items_processed: int = 0
    sequence_order: int
    metadata: Dict[str, Any] = {}


class NormalizedExecution(BaseModel):
    """
    Complete normalized execution with all events.

    This is the top-level object that contains:
    - Execution metadata (IDs, timestamps, status)
    - List of all events in chronological order

    Database mapping:
    - id: UUID (auto-generated by database)
    - n8n_execution_id: TEXT (from n8n execution JSON)
    - workflow_id: UUID (references workflows table)
    - raw_json: JSONB (original execution JSON)
    """
    execution_id: Optional[str] = None  # UUID from database, set after storage
    n8n_execution_id: str  # n8n's execution ID (e.g., "4349")
    workflow_id: Optional[str] = None  # UUID from workflows table
    n8n_workflow_id: Optional[str] = None  # n8n's workflow ID for lookup
    started_at: datetime
    finished_at: Optional[datetime] = None
    status: str  # 'success', 'error', 'timeout', 'cancelled'
    duration_ms: Optional[int] = None
    trigger_mode: Optional[str] = None
    raw_json: Dict[str, Any] = {}  # Original execution JSON
    events: List[ExecutionEvent] = []
